export enum Spells {
  Smite = "smite",
  Shield = "shield",
  Radiance = "radiance",
  Solace = "solace",
  Boon = "boon",
  AscendedBlast = "ascended-blast",
  AscendedNova = "ascended-nova",
  AscendedEruption = "ascendederuption",
  Pain = "pain",
  PainDoT = "pain-dot",
  PurgeTheWicked = "purge-the-wicked",
  PurgeTheWickedDoT = "purge-the-wicked-dot",
  Atonement = "atonement-heal",
  PenanceFriendly = "penance-friendly",
  PenanceEnemy = "penance-enemy",
  Schism = "schism",
  Evangelism = "evangelism",
  SpiritShellHeal = "spirit-shell",
  SpiritShellActivate = "spirit-shell-activate",
  Rapture = "rapture",
  ShadowMend = "shadow-mend",
  MindBlast = "mind-blast",
}
